[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "compositron"
version = "0.1.0"
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
    "pillow",
    "lmfit>=1.3.3",
    "scipy",
]
