#ifndef COMPOSITRON_SLOPE_N42_IMPORTER_H
#define COMPOSITRON_SLOPE_N42_IMPORTER_H

#include "compositron/core/measurement.h"

typedef enum {
    SUCCESS,
    MEMORY_ALLOCATION_ERROR,
    NOT_INITIALIZED_ERROR,
    INVALID_FILEPATH_ERROR,
    FILE_SYSTEM_ERROR,
    NODE_NOT_FOUND_ERROR,
    ATTRIBUTE_NOT_FOUND_ERROR,
    EMPTY_FIELD_ERROR,
    DANGLING_REFERENCE_ERROR,
    DUPLICATE_NAME_ERROR,
    INVALID_ECAL_OR_MALLOC_ERROR,
    SPECTRUM_PARSE_ERROR,
    PNG_IMPORT_ERROR,
    NOT_IMPLEMENTED_ERROR,
} SlopeN42ImportStatus;

SlopeN42ImportStatus import_SLOPE_n42(Measurement *m, const char *filename);

#endif
