# Julia compiler installation and setup instructions:
# https://github.com/JuliaLang/JuliaC.jl

default:
	mkdir -p build
	juliac \
	  --output-lib build/libcompositron \
	  --trim=safe \
	  --experimental \
	  .
